// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateHash() {
  return window['go']['hash']['Hasher']['CalculateHash']();
}
